version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: kuppet_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/kuppethomabay
    networks:
      - kuppet_network

  nginx:
    image: nginx:alpine
    container_name: kuppet_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/kuppethomabay
      - ./docker/nginx/kuppet.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - kuppet_network

  certbot:
    image: certbot/certbot
    container_name: kuppet_certbot
    volumes:
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - kuppet_network

  db:
    image: mysql:8.0
    container_name: kuppet_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kuppethomabay
      MYSQL_USER: jamadata
      MYSQL_PASSWORD: "J@maD@ta#Kp2026!Zx91"
      MYSQL_ROOT_PASSWORD: "Root@2026#Kuppet!9X"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - kuppet_network

  adminer:
    image: adminer:latest
    container_name: kuppet_adminer
    restart: unless-stopped
    networks:
      - kuppet_network

networks:
  kuppet_network:
    driver: bridge

volumes:
  dbdata:
