<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>BBF Membership Applications</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #000;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header img {
            width: 90px;
            height: auto;
            margin-bottom: 10px;
        }

        h2 {
            font-size: 18px;
            margin: 0;
        }

        .subtitle {
            font-size: 13px;
            margin-top: 5px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        th, td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #008C45; /* KUPPET GREEN */
            color: white;
        }

        tbody tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .footer {
            margin-top: 20px;
            font-size: 10px;
            text-align: center;
        }
    </style>
</head>

<body>

    {{-- HEADER --}}
    <div class="header">
        <img src="{{ public_path('assets/images/kuppet-logo.png') }}" alt="KUPPET Logo">

        <h2>HOMA BAY KUPPET BBF APPLICATIONS</h2>

        <div class="subtitle">
            Pending Membership Applications Report
        </div>
    </div>

    {{-- TABLE --}}
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Full Name</th>
                <th>TSC No</th>
                <th>Sub County</th>
                <th>Phone</th>
                <th>Category</th>
                <th>Status</th>
                <th>Submitted On</th>
            </tr>
        </thead>

        <tbody>
            @forelse($applications as $index => $app)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $app->full_name }}</td>
                    <td>{{ $app->tsc_number }}</td>
                    <td>{{ $app->subCounty->name ?? '-' }}</td>
                    <td>{{ $app->phone_number }}</td>
                    <td>{{ $app->category }}</td>
                    <td>{{ $app->status }}</td>
                    <td>{{ $app->created_at->format('d M Y') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align:center;">
                        No applications found
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {{-- FOOTER --}}
    <div class="footer">
        Generated by KUPPET Homabay BBF System • {{ now()->format('d M Y H:i') }}
    </div>

</body>
</html>