<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>BBF Membership Applications</title>

    <style>
        @page {
            size: A4 landscape;
            margin: 15px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #000;
        }

        .header {
            text-align: center;
            margin-bottom: 15px;
        }

        .header img {
            width: 80px;
            height: auto;
            margin-bottom: 5px;
        }

        h2 {
            font-size: 16px;
            margin: 0;
        }

        .subtitle {
            font-size: 12px;
            margin-top: 3px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            table-layout: fixed;
        }

        th, td {
            border: 1px solid #000;
            padding: 5px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        th {
            background-color: #008C45;
            color: white;
        }

        tbody tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .footer {
            margin-top: 15px;
            font-size: 10px;
            text-align: center;
        }

        .uppercase-text {
            text-transform: uppercase;
        }

        /* =========================
           COLUMN WIDTH CONTROL
        ========================== */

        .col-no { width: 3%; }
        .col-name { width: 12%; }
        .col-tsc { width: 8%; }
        .col-school { width: 14%; }
        .col-zone { width: 10%; }
        .col-subcounty { width: 12%; }
        .col-phone { width: 10%; }
        .col-category { width: 9%; }
        .col-status { width: 8%; }
        .col-date { width: 14%; }
    </style>
</head>

<body>

    {{-- HEADER --}}
    <div class="header">
        <img src="{{ public_path('assets/images/kuppet-logo.png') }}" alt="KUPPET Logo">

        <h2>HOMA BAY KUPPET BBF APPLICATIONS</h2>

        <div class="subtitle">
            Pending Membership Applications Report
        </div>
    </div>

    {{-- TABLE --}}
    <table>
        <thead>
            <tr>
                <th class="col-no">#</th>
                <th class="col-name">Full Name</th>
                <th class="col-tsc">TSC No</th>
                <th class="col-school">School</th>
                <th class="col-zone">Zone</th>
                <th class="col-subcounty">Sub County</th>
                <th class="col-phone">Phone</th>
                <th class="col-category">Category</th>
                <th class="col-status">Status</th>
                <th class="col-date">Submitted On</th>
            </tr>
        </thead>

        <tbody>
            @forelse($applications as $index => $app)
                <tr>

                    <td class="col-no">{{ $index + 1 }}</td>

                    {{-- NAME --}}
                    <td class="col-name uppercase-text">
                        {{ $app->full_name }}
                    </td>

                    {{-- TSC --}}
                    <td class="col-tsc">
                        {{ $app->tsc_number }}
                    </td>

                    {{-- SCHOOL --}}
                    <td class="col-school">
                        {{ $app->school_name }}
                    </td>

                    {{-- ZONE --}}
                    <td class="col-zone">
                        {{ $app->zone }}
                    </td>

                    {{-- SUB COUNTY --}}
                    <td class="col-subcounty">
                        {{ $app->subCounty->name ?? '-' }}
                    </td>

                    {{-- PHONE --}}
                    <td class="col-phone">
                        {{ $app->phone_number }}
                    </td>

                    {{-- CATEGORY --}}
                    <td class="col-category uppercase-text">
                        {{ $app->category }}
                    </td>

                    {{-- STATUS --}}
                    <td class="col-status">
                        {{ $app->status }}
                    </td>

                    {{-- DATE --}}
                    <td class="col-date">
                        {{ $app->created_at->format('d M Y') }}
                    </td>

                </tr>
            @empty
                <tr>
                    <td colspan="10" style="text-align:center;">
                        No applications found
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {{-- FOOTER --}}
    <div class="footer">
        Generated by KUPPET Homabay BBF System • {{ now()->format('d M Y H:i') }}
    </div>

</body>
</html>